name: Storm
favicon: null
layout_spectrum: 0.4200972232501954
typography_spectrum: 0.2728109387680888
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.638831848744303
  lightness: 0.08012356678955257
  saturation: 0.5345864596311003
  rhythmicContrast: 0.4348179192747921
purpose: []
